const wordBankMini = [
  "ABACUS", "ADMIRE", "ANCHOR", "ANIMAL", "APATHY", "ARCHER", "ARTIST", "ASCENT", "BANANA", 
  "BEAUTY", "BEYOND", "BOTTLE", "BRANCH", "BUCKET", "CAMERA", "CANDLE", "CANVAS", "CASTLE", 
  "CASUAL", "CHANCE", "CHARGE", "CHORUS", "CIRCLE", "CIRCUS", "CLINIC", "COFFEE", "COLUMN", 
  "COMEDY", "COMMON", "COOKIE", "COTTON", "COUPLE", "CREATE", "DANGER", "DECADE", "DEFINE", 
  "DELUXE", "DEMAND", "DESERT", "DESIGN", "DETAIL", "DEVICE", "DIVIDE", "DOCTOR", "DRAGON", 
  "DRAWER", "EFFORT", "EIGHTH", "ELAPSE", "ELEGANT", "ENERGY", "ENGINE", "ENLIST", "ESCAPE", 
  "ETHICS", "EXCITE", "EXOTIC", "FABRIC", "FAMILY", "FARMER", "FATHER", "FELINE", "FIGURE", 
  "FINISH", "FLIGHT", "FLOWER", "FOREST", "FORGET", "FOSSIL", "FROZEN", "GARDEN", "GENDER", 
  "GENTLE", "GLOBAL", "GOLDEN", "GROWTH", "HARBOR", "HEALTH", "HIKING", "HORIZON", "HUNTER", 
  "IGNITE", "IMPACT", "INDIGO", "INSECT", "INTENT", "ISLAND", "JACKET", "JUNGLE", "KEEPER", 
  "KITTEN", "LADDER", "LEGACY", "LESSON", "LEGEND", "LETTER"
];

export default wordBankMini;

